### ISSUE TITLE
Add manual routing option

### ISSUE THREAD

**Issue by edgarbilliet** [FreemapSlovakia/freemap-v3-react#522] opened 2020-05-27 14:42 UTC
Is it possible to add a manual drawing option? E.g. for when certain paths or roads are not routable or when you want to draw over satellite images which show roads that are not shown on any map. Currently there is no going back from drawing mode.

Would be handy as well if manual option would work just between two existing waypoints and not only at the end of your route.

**Comment by zdila** [comment] 2020-08-07 13:33
Duplicate of #505 (which is reported in Slovak language but you can try to use google translate and feel free to comment there in english)

**Closed by zdila** 2020-08-07 13:33 UTC
