### ISSUE TITLE
Indicate the shot direction when showing the photo layer

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-v3-react#634] opened 2021-11-10 07:35 UTC
Some cameras/smartphones include EXIF information about the direction the device was pointed in, when a photo was made. It would be beneficial to extract that info and show it on the map, for example in the form of a modified photo placement icon. See for example how JOSM uses arrows to achieve the same objective. Attached is also a part of the EXIF info containing the directional data.

<img width="546" alt="Screenshot 2021-11-10 at 08 32 02" src="https://user-images.githubusercontent.com/3430677/141069293-f5dbb24e-9cee-43c7-9c68-65c6c566c9fb.png">

<img width="322" alt="Screenshot 2021-11-10 at 08 24 51" src="https://user-images.githubusercontent.com/3430677/141069450-fd97df89-1ce6-4fbd-82ed-821ca026257d.png">

**Comment by jose1711** [comment] 2021-11-19 12:09
That's an interesting idea. In addition to direction I think it would be nice to also indicate a FOV e. g. in a way how Mapillary does that:
![obrázok](https://user-images.githubusercontent.com/1406222/142620586-e05c7433-f8c4-4cb3-ab07-c3af35d0907b.png)

**Comment by zdila** [comment] 2021-11-19 12:21
Duplicate of #213

**Closed by zdila** 2021-11-19 12:21 UTC
